#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yuuki Tsubouchi
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans=0
ans1=0
ans2=1
for line in sys.stdin:
    try:
        ans += int(line)
        ans1 -= int(line)
        ans2 *= int(line)
    except:
        ans +=float(line)
        ans1 -=float(line)
        ans2 *=float(line)

print(ans)
print(ans1)
print(ans2)


















